version: '3.1'

services:
  client:
    build: ./client
    ports:
      # Nginx static server:
      - "8080:80"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      # Express API:
      - "8001:8001"
      # Websocket server:
      - "3000:3000"
    environment:
      PORT: 8001
      MONGODB_URI: mongodb://mongo:27017
      WEBSOCKET_PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      # MongoDB admin dashboard:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
